- README.md
> chore: update date

- cips/cip-10.md
- cips/cip-network-upgrade.md
Adds a draft CIP defining a protocol for coordinated upgrades
> cip for coordinated network upgrades

- cips/cip-9.md
This PR ads Test Cases to CIP-9 for implementing Packet Forward Middleware
> Update cip-9.md (PFM) with Test Cases

- cips/cip-5.md
Update CIP-5 based on community feedbacks.
And move CIP-5 to review stage.
> Move CIP-5 to review

- cips/cip-12.md
Adding test case assertions to CIP 12 as well as a link to the existing e2e tests in ibc-go for ICS29 behavior.
> CIP 12: Add Test Cases

- README.md
> feat: update readme for cdc3

- cips/cip-6.md
> feat: move cip-6 to Last Call

- cips/cip-9.md
> Move cip-9 from Draft to Review

- cips/cip-12.md
Changing status from draft to review
> Update cip-12 status.md

- README.md
Adds tweet thread and recording from CDC3 (#40)
> feat: add tweet thread and recording from cdc 3

- cips/cip-1.md
Adds Ethan Buchman (@ebuchman) as CIP editor to CIP-1.
> feat: add ebuchman as CIP editor

- .github/workflows/pr-review-requester.yml
This PR fixes the auto-reviewer workflow, based on https://github.com/celestiaorg/CIPs/pull/52#issuecomment-1916915820
> feat: fix workflow

- README.md
> feat: update README.md with CDC 4

- cips/cip-4.md
- expands reference implementation with details for sampling window for light nodes
- explains options for storage pruning
- updates CIP author
- updates link to PR for upcoming pruning PR in celestia-node in CIP preamble
> feat: expand CIP4 with reference implementation

- cips/cip-6.md
It was agreed upon amongst the core engineers after several discussions that the minimum gas price should be modifiable by governance. This PR updates CIP 6 to reflect that.
> Modify CIP-6 to include the resolution that minimum gas price be modifiable by governance

- .github/auto_request_review.yml
This PR updates number of reviewers from 2 to 3, allowing all 3 current editors to be tagged for reviews.
> feat: Update auto_request_review.yml

- cips/cip-9.md
This moves CIP-9 to Last Call, with last call deadline of 2024-02-20.
> feat: update cip-9 to Last Call

- cips/cip-4.md
This changes instances of "30 days" to "30 days + 1 hour worth of seconds (2595600 seconds)".
> feat: update cip-4 to 30 days + 1 hour worth of seconds (2595600 seconds), move to Final

- README.md
> feat: update readme with cdc 4 call notes

- wgs/README.md
Links were not correct in suggestion, this fixes them.
https://www.loom.com/share/d68cd81b368846e99f170581e28860ad?sid=ddb2a139-2f23-494d-b7bd-3c06d5e874d3
> fix: links to wg folders

- cips/cip-17.md
This PR adds the meta CIP for the lemongrass hardfork.
> Add Meta CIP-17 for the lemongrass hardfork

- README.md
> notes/stream link for call #5

- cips/cip-9.md
Ref: https://x.com/JoshCStein/status/1759973307682832505?s=20
> feat: Update cip-9.md to Final

- cips/cip-6.md
Ref: https://x.com/JoshCStein/status/1759973768112574768?s=20
> feat: Update cip-6.md to Last Call

- cips/cip-12.md
Ref: https://x.com/JoshCStein/status/1759974278542631384?s=20
> feat: Update cip-12.md to Last Call

- README.md
> notes/stream link for call #6

- README.md
> feat: add CIP-17 to readme

- wgs/zk/README.md
> Add recording links to the Zk working group meetings

- cips/cip-14.md
> Change cip-14 from draft to review.md

- cips/cip-19.md
> cip-19: Review status

- README.md
> notes/stream link for call #7

- cips/cip-18.md
I am not sure if there is anything else required but I would like to move this CIP into review
> chore: move CIP-18 into review

- cips/cip-12.md
Per the discussion on [All Core Devs 8](https://github.com/celestiaorg/CIPs/issues/107) re the missing details in the Security considerations section and the writeup here: https://forum.celestia.org/t/cip-relayer-incentivisation-middleware/1383/6
Moving back to review until this is updated.
Resolves #123
> Move CIP 12 back to Review

- README.md
> notes/stream link for call #8 and #9

- cips/cip-17.md
An action item from today's call was to express my desire for including CIP-20 in Lemongrass
> feat: add cip-20 to Lemongrass

- wgs/da/README.md
> docs: update DA working group past meetings

- cips/cip-10.md
As well as the status update, this adds some more information on the upgrade process and provides a list of test cases.
> Move cip-10 to final call and add a few more clarifying remarks

- cips/cip-20.md
Move CIP-20 to review and populate the security considerations section.
> docs(cip-20): move to review

- cips/cip-20.md
Based on discussion in https://github.com/celestiaorg/CIPs/issues/134
> docs(cip-20): move to last call

- cips/cip-17.md
We just decided to revert a decision from yesterday and so we're now planning on including price enforcement in Lemongrass.
> docs(cip-17): add price enforcement to Lemongrass

- cips/cip-17.md
- cips/cip-20.md
- cips/cip-6.md
The CIPs that are prerequisites to Lemongrass (CIP-17) have all been moved to final so now CIP-17 can move from draft to review or last call.
> docs: update status for CIP-6, CIP-17, CIP-20

- wgs/zk/README.md
update working group page with recording links
> Update Working group page with recording links

- wgs/zk/README.md
Adds open questions gathered from the last call to the read-me. Will be updated periodically.
> Add open questions to readme

- README.md
> notes/stream link for call #10 and #11

- README.md
> notes/stream link for call #12

- README.md
> fix: add cip-22 to README

- cips/README.md
- cips/SUMMARY.md
Resolves #173 (actually this time, after deployed to cips.celestia.org)
> fix: link to homepage

- cips/README.md
- cips/cip-22.md
Move status to Review and adapt CIP with updated specification after https://github.com/celestiaorg/celestia-app/issues/3632
> Move status to Review and adapt CIP with updated specification

- cips/README.md
> docs: add CDC 15 to site

- cips/cip-24.md
I forgot to add an extra `)` in the review.
> docs(CIP-24): fix typo

- cips/cip-1.md
> CIP-1: update Preamble section for header table

- .github/auto_request_review.yml
- cips/cip-1.md
> docs: move yaz to emeritus

- cips/README.md
> docs: change date for CDC16 to next week 4 Sept.

- cips/README.md
> docs: add recording for 16 and link to 17

- cips/cip-24.md
Moving cip-24 to status - Review
> chore: move cip-24 to review

- cips/SUMMARY.md
Adds cip-25.md to the SUMMARY.md page, which allows it to render in the menu and build for the site.
> docs: add cip-25 to summary.md

- cips/README.md
> docs: add cdc 17 notes and 18 to readme

- cips/cip-21.md
> Docs: move CIP-21 to Final

- cips/cip-24.md
> Docs: Update cip-24.md to Final

- cips/cip-25.md
> docs: move CIP 25 to Review

- cips/cip-25.md
Discovered while reviewing https://github.com/celestiaorg/CIPs/pull/229#pullrequestreview-2382181303
> fix(cip-25): link

- cips/cip-25.md
- cips/cip-26.md
- cips/cip-27.md
- cips/cip-28.md
> docs: CIPs 25-28 to Last Call

- cips/cip-25.md
- cips/cip-26.md
- cips/cip-27.md
- cips/cip-28.md
> docs: move CIPs 25-28 to Final

- cips/README.md
> docs: add CDC 20 to list

- cips/README.md
> docs: add 20 notes and 21 reminder

- cips/README.md
> Update README.md with cdc 21-22

- cips/README.md
> docs: update readme

- cips/wgs/da/README.md
Adds notes for lates da wg call.
> update da wg meeting notes

- cips/README.md
> docs: Update README.md

- cips/README.md
- cips/SUMMARY.md
- cips/cip-29.md
- cips/cip-31.md
> docs: add cip-31 to site

- cips/cip-032.md
Would be nice to move these to review before the core devs call on Wednesday. cc: @jcstein @cmwaters
> docs(cip-32): move to review

- cips/cip-031.md
Is there a reference implementation I can add to the detailed design / reference implementation section? @tac0turtle
> docs(cip-31): move to review

- cips/README.md
> docs: add call 28

- cips/cip-029.md
- cips/cip-030.md
- cips/cip-032.md
Moves CIPs 29, 30, 32 to Final as discussed in Core Devs Call 27: https://github.com/celestiaorg/CIPs/issues/278
> docs: cips to Final from CDC 27

- cips/cip-002.md
- cips/cip-003.md
- cips/cip-016.md
- cips/cip-017.md
- cips/cip-025.md
- cips/cip-033.md
- cips/cip-034.md
> docs: fix link in CIP-34 supercede section, add links to all requires sections

- cips/cip-031.md
add detail that only the token in the vesting schedule will be added to it, not others
> chore: add reward token detail

- cips/README.md
> docs: add tweet thread from cdc 27

- cips/README.md
> docs: update readme with cdc 29

- cips/cip-015.md
We're not actively working on this or pushing it forward.
> docs(cip-15): withdraw

- cips/cip-019.md
> docs: move cip-19 to last call

- cips/cip-023.md
> docs: withdraw CIP-23

- cips/cip-034.md
Removes sampling window from CIP . Builds on top of https://github.com/celestiaorg/CIPs/pull/309
> Remove sampling window from CIP

- cips/cip-036.md
Created a new forum post for dedicated discussion
> Update cip-036.md forum post link

- cips/README.md
> docs: add calls 30-34 to readme

- cips/README.md
Adds links to CDCs 35&46, notes from 35. Format table.
> chore: add to readme, site, format table

- cips/cip-002.md
- cips/cip-042.md
> chore: move 42 to final
