cips/cip-4.md, cips/cip-pruning-window.md
[Rendered](https://github.com/musalbas/CIPs/blob/musalbas/cip-pruning/cips/cip-pruning-window.md)
Discussion: https://forum.celestia.org/t/cip-standardize-data-expiry-time-for-pruned-nodes/1326
=> CIP: Standardize data expiry time for pruned nodes

cips/cip-1.md
1. Because even the title of this cip is longer than 44 chars, I believe the unit of limit should be 'words'.
2. Adding a reference for relative rules could make it more senseful.
3. Do not need these rules that conflict with this cip itself.
Besides these modifications, after more thinking, I feel the Cip-1 should not be so complex. Just like the U.S. Constitution which has only rationale, rights, responsibility, and reference, but not the details of type, process, format, header, and editor. I believe these should be in separated cips because they could be changed more frequently.
=> Edit some text so that be more senseful.

cips/cip-13.md, cips/cip-onchain-governance-params.md
Adds a CIP to reference specs active on Mainnet based on what exists here: https://celestiaorg.github.io/celestia-app/specs/params.html
=> Add CIP for onchain gov params

cips/cip-11.md
We're putting the refund unspent gas line of work on pause because the mitigation strategies to the DoS attack are overly complicated.
=> docs: move CIP-11 to withdrawn

cips/cip-11.md
> I see this CIP was withdrawn. I think that means it should be updated with a withdrawal-reason, per [CIPs/cips/cip-1.md at main · celestiaorg/CIPs · GitHub](https://github.com/celestiaorg/CIPs/blob/main/cips/cip-1.md#cip-header-preamble) ?
See https://forum.celestia.org/t/cip-refund-unspent-gas/1374/2
=> chore(cip-11): add withdrawal reason

cips/cip-15.md
=> docs: move params to be gov unmodifiable

cips/cip-4.md
Sampling window (light nodes sampling blocks) = 30 days
Pruning window (full nodes storing and serving blocks) = 30 days + 1
**Question:**
Should we make clear definitions in the CIP to differentiate pruning window from sampling window?
=> fix(cips): Clarify sampling window vs pruning window

cips/cip-6.md
In the spirit of CIP-13, added a single-row table summarizing the new parameter.
Would be good to set a standard to have this table in any CIP that introduces a new parameter or modifies one so it can easily be copied into CIP-13 if/when it's approved.
In this vein it wasn't entirely clear to me what the param store will be called. This CIP mentions it will be a new param.Subspace but doesn't name it, so I'm optimistically calling it `gas` but feel free to correct. That said it's not clear to me why this shouldn't just go under `auth` along with eg. `auth.TxSizeCostPerByte`? 
Also updated the title to be a bit more descriptive
=> Update cip-6.md title and add summary table

cips/cip-draft_msrgpi_abbrev.md
Add a CIP to make two parameters unchangeable for online governance.
Motivation: [celestiaorg/CIPs/pull#68](https://github.com/celestiaorg/CIPs/pull/68)
Forum: https://forum.celestia.org/t/cip-make-security-related-governance-parameters-immutable/1566
=> docs: CIP for make security related governance parameters immutable

cips/cip-1.md, cips/cip-template.md
Per the discussion on Dev Call 6 today, in order to make it easy to keep CIP-13 up-to-date, CIP's should include a parameter section that specifies any parameter changes. 
I added it as a separate Parameters section but it could just as well go into the Specification section if that's preferred.
=> Update cip-template.md with parameter section

.github/auto_request_review.yml, cips/cip-1.md
https://github.com/celestiaorg/CIPs/blob/2fe05c0e58fcb9dc69cb278b8f7b880f89137366/cips/cip-2.md?plain=1#L32
=> feat: add rootulp as CIP editor

README.md, cips/cip-18.md, cips/cip-tx-interface.md
I have submitted this as part of the `Interface` category, but it may be better suited as a CRC. Let me know and I can easily change it
=> CIP-18: Standardised Gas and Pricing Estimation Interface

cips/cip-19.md
Extends the cip-19 with new identifier/container.
=> cip-19: add eds identifier/container

cips/cip-6.md
=> docs(cip-6): update the reference implementation

cips/cip-19.md
This is a protocol-breaking change for Shwap. Initially, containers kept the identifiers as a first field in them. However, we decided to decouple those.
The Bitswap protocol dictates the requirement to have IDs in containers and this enforces certain limitations and overhead for the core Shwap containers. However, we want to use the containers outside of the Bitswap composition context, and thus, we need to remove this requirement from the containers. Furthermore, we design Shwap in a protocol-agnostic way, and Bitswap enforcing limits on containers is inconsistent with that. 
As Bitswap still _requires_ coupling between data and identifiers, we introduce container adapters for the Bitswap composition to address that.
We rename `Data` -> `RowNamespaceData` and increase verbosity to …
=> cip-19!: breaking Shwap protocol improvements

cips/cip-19.md
This allows the server to choose which half of the row to serve. In special cases, this saves erasure coding computation for the server, while the client side has to do this computation anyway to verify the served data. For example, the server may store only the right (parity) side of the row and instead of computing the previously strict left side to be served, it can serve the stored right one right-away. 
Besides, this PR brings minor little proto improvements across the containers
This change was supposed to land in #128, but the PR was merged very quickly so I am making a new one.
=> cip-19: add HalfSide field to Row

cips/cip-14.md
CIP-14 hasn't had any significant changes recently. Same for the relevant [forum post](https://forum.celestia.org/t/moving-toward-safer-and-more-aligned-tia-liquid-staking/1422).
I propose moving it to last call with a deadline two weeks from now.
=> docs(cip-14): move to last call

cips/cip-17.md
Remove price enforcement ([CIP-6](https://github.com/celestiaorg/CIPs/blob/main/cips/cip-6.md)) from the list of included CIPs in the Lemongrass hard-fork. We recently decided that this feature needs to be tweaked before it provides significant value so we're withdrawing it from inclusion in the Lemongrass hard-fork but CIP-6 may be considered for future hard-forks.
=> docs(cip-17): remove price enforcement

cips/cip-6.md
Motivated by forum comments [here](https://forum.celestia.org/t/cip-price-enforcement/1351/5) and [here](https://forum.celestia.org/t/cip-price-enforcement/1351/7).
=> docs(cip-6): update MinimumGasPrice default

cips/cip-10.md, cips/cip-14.md, cips/cip-6.md
Moves CIP-6 to last call and suggests a deadline two weeks from today.
Moves CIP-10 and CIP-14 to final because we passed the last call deadline.
=> docs: update status CIP-6, CIP-10, CIP-14

cips/cip-1.md
The convention followed thus far has to been used monotonically increasing CIP numbers and not the PR number.
=> docs(cip-1): update CIP number information

cips/cip-19.md
While the status of the CIP is still `Review`, we want to make a protocol-breaking amendment to Shwap prompted by the ongoing production-ready implementation. This change simplifies the protocol, particularly the Bitswap composition, by making a single protobuf definition of a Block instead of N definitions per every current and future Container type.
This change is motivated by a desire to make it easier for Shwap to extend horizontally in the abstract specification and its implementations. Previously, the new container would have to be added to both the core Shwap container specification and the Bitswap composition. Now, only a single place needs to be updated(and Bitswap codec registry). 
Besides, decoupling Shwap's and composition's protobuf definitions significantly improved cohesion …
=> cip-19!: simplify Bitswap compostion

cips/cip-22.md, cips/cip-noindex.md
CIP about removing the blobstartIndex from the Wrapped Transaction
=> CIP-22: Remove blobStartIndex from PFBs

cips/cip-prevote.md
Supercedes: https://github.com/celestiaorg/CIPs/pull/164
=> CIP: Coordinated prevote times

cips/README.md, cips/SUMMARY.md, cips/notes/README.md, cips/notes/cdc-15.md
=> docs: notes from cdc 15

cips/cip-17.md
[Test links here
](https://github.com/celestiaorg/CIPs/blob/jcs/update-cip-17-links/cips/cip-17.md#included-cips)
=> docs: use relative link on cip-17 for site + github functionality

cips/cip-19.md
Correct specification of reed solomon algorithm used to encode/reconstruct the other half of shares present in a Row container.
Consensus uses leopard gf8 for squares with width not exceeding 256 shares.
Source: [default codec](https://github.com/celestiaorg/celestia-app/blob/main/pkg/appconsts/global_consts.go#L41) leading to [rsmt2d leopard construction](https://github.com/celestiaorg/rsmt2d/blob/main/leopard.go#L61) using [leopardAlways](https://github.com/klauspost/reedsolomon/blob/master/options.go#L293) which [selects between gf8 and gf16
](https://github.com/klauspost/reedsolomon/blob/master/reedsolomon.go#L420)
=> docs(cip-19): fix the reed solomon algorithm used for rows

cips/cip-24.md
We want to include this in v3 hence the shorter last call deadline of ~1 week. We'd like to get v3 on Arabica by Oct 7.
=> docs(cip-24): move to last call

cips/README.md, cips/cip-25.md
After discussion in slack and for fall theme. https://celestia-team.slack.com/archives/C03324EKQ1Y/p1727880219189889?thread_ts=1727811328.742149&cid=C03324EKQ1Y
=> docs: update to Ginger for v3 name

cips/cip-25.md
Updates Ginger Draft from suggestion by @rootulp in https://github.com/celestiaorg/CIPs/pull/216#discussion_r1795485634
Adds CIP-10 to Meta CIP for Ginger network upgrade
=> feat: add six second CIP and compute CIP to ginger draft

cips/README.md, cips/SUMMARY.md, cips/cip-25.md, cips/cip-26.md, cips/cip-6-second-blocks.md
=> feat: Versioned timeouts CIP draft

cips/cip-26.md, cips/cip-27.md, cips/cip-28.md
=> docs: move CIPs 26,27,28 to Review

cips/wgs/README.md
While digging around the CIPs repo looking to catch up on what i'd missed the last few months, i noticed there was a front `README` link to the wgs which acted as a landing page, that then linked to each folder for each WG, but those were set as "index.html" and thus would 404 in GitHub. 
I've updated the top level /wg/README to link to each WG's folder where GitHub automatically will render the main README.md
eg: https://github.com/ramin/CIPs/blob/ramin/update-wg-links/cips/wgs/README.md
=> docs: remove index.html links in top level wg README links 

cips/cip-18.md
This PR makes a few minor modifications to CIP 18:  Standardised Gas and Pricing Estimation Interface
- Remove the reference implementation section. Client and server implementations in the light and consensus node respectively will have their own ADRs that eventually can be linked in this CIP
- Add an optional `TxPriority` field to indicate the urgency for a transaction to be finalized in a block. It has three levels: low, medium, and high.
- Modify the APIs to have two methods: requesting just the gas price and requesting the gas price and the gas. The latter will be used for non-PFB transactions.
=> CIP 18: Add tx priority to requests 

cips/cip-30.md
This cip proposes a change to the distribution module, the change stops auto claiming of rewards when modifying delegation shares (delegation, redelgation, unbonding) and makes the movement of funds from the distribution module to a users account explicit.
=> cip: prevent auto claiming of rewards. 

cips/cip-12.md
Closes https://github.com/celestiaorg/CIPs/issues/120 because we don't need to add security considerations if we withdraw the proposal.
Withdraw CIP-12 because ICS-29 will be removed from ibc-go v10. See https://celestia-team.slack.com/archives/C047X1T6ERK/p1740423665065499
cc: @womensrights @AdityaSripal
=> docs(cip-12): withdraw

cips/cip-13.md
CIP-13 is a maintenance burden and hasn't been updated to include new parameters added in v2 or v3. It also hasn't been updated to account for governance modifiable changes. This PR withdraws the CIP which seems safe because it never progressed past **Draft**.
Closes https://github.com/celestiaorg/CIPs/issues/204 
Closes https://github.com/celestiaorg/CIPs/issues/113
Closes https://github.com/celestiaorg/CIPs/pull/115
=> docs: withdraw cip-13

cips/cip-033.md
Oops I didn't notice that the `requires` field in the table was empty
=> docs(cip-33): add prerequisite CIPs

cips/cip-013.md, cips/wgs/zk/overview.md
The site renders the tip callout as "[!TIP]" on the site.
=> docs: fix site rendering

cips/cip-031.md
This pr updates the cip-31 guidelines and implementation in order to make the design and flow as simple as possible. 
closes https://github.com/celestiaorg/CIPs/issues/284
=> CIP-31: updates according to the implemention

cips/cip-034.md
Based on the conversation at yesterdays core devs call, I have removed reference to the header pruning CIP and tried to make it independent focusin on the fact that the sampling window needs to be within trustingPeriod which is currently 14 days
=> CIP 34: Improve the description and remove reference to header pruning

cips/cip-031.md, cips/cip-033.md
Move CIP-31 to final because we're done amending the CIP based on the implementation.
Move CIP-33 to final because now all the prerequisite CIPs are final
=> chore: move cip-31, cip-33 to final

cips/README.md, cips/SUMMARY.md, cips/cip-038.md
adds cip-38, which is just a reference to the spec for using pull base broadcast trees. discussions can be found https://github.com/celestiaorg/celestia-app/pull/4285
=> docs: add CIP-38 High-Throughput Block Recovery

cips/README.md, cips/SUMMARY.md, cips/cip-039.md
This cip proposes removing the token filter for Hyperlane and IBC. This makes Celestia a more effective routing layer for access to non-TIA assets for Celestia apps.
=> cip: Remove token filter for Hyperlane and IBC

cips/README.md, cips/cip-038.md
Since I believe the increasing in the throughput parameters should be in conjunction with the new block propagation protocol i.e. because of the proposed changes here we can increase block size to 128MB, I have decided to amend this CIP with the necessary parameter changes
=> Amend CIP-38 to also increase block size to 128MB and tx size to 8MB

cips/cip-040.md
Updates the existing CIP to match what we're implementing
=> docs: update the privval extension CIP to match the expected implementation
